# default
spring.application.name=test2
server.port=8082

# ActiveMQ
activemq.brokerUrl=tcp://localhost:61616
activemq.username=admin
activemq.password=admin
activemq.queues=queue1,queue2,queue3,queue4
activemq.topics=topic1,topic2,topic3,topic22,Consumer.test2.VirtualTopic.topic99

activemq.queueSessionMode=0
activemq.topicSessionMode=2
activemq.clientId=client2
activemq.retransmit=true
# ??? ??
#activemq.queueSessionMode=1
#activemq.topicSessionMode=1
