# default
spring.application.name=test1
server.port=8081

# ActiveMQ
activemq.brokerUrl=tcp://localhost:61616
activemq.username=admin
activemq.password=admin
activemq.queues=queue1,queue2,queue3
activemq.topics=topic1,topic2,topic3,topic11,Consumer.test1.VirtualTopic.topic99
# ???? ??
activemq.queueSessionMode=0
activemq.topicSessionMode=2
activemq.clientId=client1 
activemq.retransmit=true
# ??? ??
#activemq.queueSessionMode=1
#activemq.topicSessionMode=1




