#activemq.brokerUrl=tcp://localhost:61616
#activemq.username=admin
#activemq.password=admin
#activemq.topics=topic1,topic2,topic3,topic4,topic11
#activemq.queues=queue1,queue2,queue3
activemq.queueSessionMode=0
activemq.topicSessionMode=0
#activemq.clientId=client1
#activemq.retransmit=true