# default
spring.application.name=test3
server.port=8083

# ActiveMQ
activemq.brokerUrl=tcp://localhost:61616
activemq.username=admin
activemq.password=admin
activemq.queues=queue1,queue2,queue3
activemq.topics=topic1,topic2,topic3,topic33,Consumer.test3.VirtualTopic.topic99
# ???? ??
activemq.queueSessionMode=0
activemq.topicSessionMode=2
activemq.clientId=client3
activemq.retransmit=true
# ??? ??
#activemq.queueSessionMode=1
#activemq.topicSessionMode=1